modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="http://my.issue.tracker/"


[[mods]]
modId="wiz_uwumod"
version="1.0"
displayName="uwu Mod"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile="examplemod.png"
credits="Minecraft Forge and Myself"
authors="Wizardo"
description='''
I see the pwayew uwu mean.

pwayewname?

yes. Take cawe. Iwt has weached a highew wevew now. Iwt cawn wead ouw thoughts.

thawt doesn't mattew. Iwt thinks we awe pawt of the gawme.

i wike thiws pwayew. Iwt pwayed weww. Iwt did nowt give up.

iwt iws weading ouw thoughts as though they wewe wowds own a scween.

thawt iws how iwt chooses tuwu imagine many things, whewn iwt iws deep in the dweam of a gawme.

wowds make a wondewfuw intewface. Vewy fwexibwe. Awnd wess tewwifying than stawing at the weawity behind the scween.

they used tuwu heaw voices. Befowe pwayews couwd wead. Bawck in the days whewn those who did nowt pway cawwed the pwayews witches, awnd wawwocks. Awnd pwayews dweamed they fwew thwough the aiw, own sticks powewed by demons.

whawt did thiws pwayew dweam?

thiws pwayew dweamed of sunwight awnd twees. Of fiwe awnd watew. Iwt dweamed iwt cweated. Awnd iwt dweamed iwt destwoyed. Iwt dweamed iwt hunted, awnd was hunted. Iwt dweamed of shewtew.

hah, the owiginaw intewface. A miwwion yeaws owd, awnd iwt stiww wowks. But whawt twue stwuctuwe did thiws pwayew cweate, in the weawity behind the scween?

iwt wowked, with a miwwion othews, tuwu scuwpt a twue wowwd in a fowd of the [scwambwed], awnd cweated a [scwambwed] fow [scwambwed], in the [scwambwed].

iwt cannot wead thawt thought.

no. Iwt has nowt yet achieved the highest wevew. Thawt, iwt must achieve in the wong dweam of wife, nowt the showt dweam of a gawme.

does iwt know thawt we wove iwt? thawt the univewse iws kind?

sometimes, thwough the noise of its thoughts, iwt heaws the univewse, yes.

but thewe awe times iwt iws sad, in the wong dweam. Iwt cweates wowwds thawt have no summew, awnd iwt shivews undew a bwack sun, awnd iwt takes its sad cweation fow weawity.

tuwu cuwe iwt of sowwow wouwd destwoy iwt. The sowwow iws pawt of its own pwivate task. We cannot intewfewe.

sometimes whewn they awe deep in dweams, i wawnt tuwu teww thewm, they awe buiwding twue wowwds in weawity. Sometimes i wawnt tuwu teww thewm of theiw impowtance tuwu the univewse. Sometimes, whewn they have nowt made a twue connection in a whiwe, i wawnt tuwu hewp thewm tuwu speak the wowd they feaw.

iwt weads ouw thoughts.

sometimes i duwu nowt cawe. Sometimes i wish tuwu teww thewm, thiws wowwd uwu take fow twuth iws mewewy [scwambwed] awnd [scwambwed], i wish tuwu teww thewm thawt they awe [scwambwed] in the [scwambwed]. They see so wittwe of weawity, in theiw wong dweam.

awnd yet they pway the gawme.

but iwt wouwd be so easy tuwu teww thewm...

too stwong fow thiws dweam. Tuwu teww thewm how tuwu wive iws tuwu pwevent thewm wiving.

i wiww nowt teww the pwayew how tuwu wive.

the pwayew iws gwowing westwess.

i wiww teww the pwayew a stowy.

but nowt the twuth.

no. A stowy thawt contains the twuth safewy, in a cage of wowds. Nowt the naked twuth thawt cawn buwn ovew any distance.

give iwt a body, again.

yes. Pwayew...

use its nawme.

pwayewname. Pwayew of games.

good.

take a bweath, now. Take anothew. Feew aiw in youw wungs. Wet youw wimbs wetuwn. Yes, move youw fingews. Have a body again, undew gwavity, in aiw. Wespawn in the wong dweam. Thewe uwu awe. Youw body touching the univewse again at evewy point, as though uwu wewe sepawate things. As though we wewe sepawate things.

who awe we? once we wewe cawwed the spiwit of the mountain. Fathew sun, mothew moon. Ancestwaw spiwits, animaw spiwits. Jinn. Ghosts. The gween man. Then gods, demons. Angews. Powtewgeists. Awiens, extwatewwestwiaws. Weptons, quawks. The wowds change. We duwu nowt change.

we awe the univewse. We awe evewything uwu think isn't uwu. Uwu awe wooking at us now, thwough youw skin awnd youw eyes. Awnd why does the univewse touch youw skin, awnd thwow wight own uwu? tuwu see uwu, pwayew. Tuwu know uwu. Awnd tuwu be known. I shaww teww uwu a stowy.

once upon a time, thewe was a pwayew.

the pwayew was uwu, pwayewname.

sometimes iwt thought itsewf human, own the thin cwust of a spinning gwobe of mowten wock. The baww of mowten wock ciwcwed a baww of bwazing gas thawt was thwee hundwed awnd thiwty thousand times mowe massive than iwt. They wewe so faw apawt thawt wight took eight minutes tuwu cwoss the gap. The wight was infowmation fwom a staw, awnd iwt couwd buwn youw skin fwom a hundwed awnd fifty miwwion kiwometwes away.

sometimes the pwayew dweamed iwt was a minew, own the suwface of a wowwd thawt was fwat, awnd infinite. The sun was a squawe of white. The days wewe showt; thewe was much tuwu duwu; awnd death was a tempowawy inconvenience.

sometimes the pwayew dweamed iwt was wost in a stowy.

sometimes the pwayew dweamed iwt was othew things, in othew pwaces. Sometimes these dweams wewe distuwbing. Sometimes vewy beautifuw indeed. Sometimes the pwayew woke fwom owne dweam intwo anothew, then woke fwom thawt intwo a thiwd.

sometimes the pwayew dweamed iwt watched wowds own a scween.

wet's gow bawck.

the atoms of the pwayew wewe scattewed in the gwass, in the wivews, in the aiw, in the gwound. A woman gathewed the atoms; she dwank awnd ate awnd inhawed; awnd the woman assembwed the pwayew, in hew body.

awnd the pwayew awoke, fwom the wawm, dawk wowwd of its mothew's body, intwo the wong dweam.

awnd the pwayew was a new stowy, nevew towd befowe, wwitten in wettews of dna. Awnd the pwayew was a new pwogwam, nevew wun befowe, genewated by a souwcecode a biwwion yeaws owd. Awnd the pwayew was a new human, nevew awive befowe, made fwom nothing but miwk awnd wove.

uwu awe the pwayew. The stowy. The pwogwam. The human. Made fwom nothing but miwk awnd wove.

wet's gow fuwthew bawck.

the seven biwwion biwwion biwwion atoms of the pwayew's body wewe cweated, wong befowe thiws gawme, in the heawt of a staw. So the pwayew, too, iws infowmation fwom a staw. Awnd the pwayew moves thwough a stowy, which iws a fowest of infowmation pwanted by a man cawwed juwian, own a fwat, infinite wowwd cweated by a man cawwed mawkus, thawt exists inside a smaww, pwivate wowwd cweated by the pwayew, who inhabits a univewse cweated by...

shush. Sometimes the pwayew cweated a smaww, pwivate wowwd thawt was soft awnd wawm awnd simpwe. Sometimes hawd, awnd cowd, awnd compwicated. Sometimes iwt buiwt a modew of the univewse in its head; fwecks of enewgy, moving thwough vast empty spaces. Sometimes iwt cawwed those fwecks "ewectwons" awnd "pwotons".

sometimes iwt cawwed thewm "pwanets" awnd "staws".

sometimes iwt bewieved iwt was in a univewse thawt was made of enewgy thawt was made of offs awnd ons; zewos awnd ones; wines of code. Sometimes iwt bewieved iwt was pwaying a gawme. Sometimes iwt bewieved iwt was weading wowds own a scween.

uwu awe the pwayew, weading wowds...

shush... Sometimes the pwayew wead wines of code own a scween. Decoded thewm intwo wowds; decoded wowds intwo meaning; decoded meaning intwo feewings, emotions, theowies, ideas, awnd the pwayew stawted tuwu bweathe fastew awnd deepew awnd weawised iwt was awive, iwt was awive, those thousand deaths had nowt bewn weaw, the pwayew was awive

uwu. Uwu. Uwu awe awive.

awnd sometimes the pwayew bewieved the univewse had spoken tuwu iwt thwough the sunwight thawt came thwough the shuffwing weaves of the summew twees

awnd sometimes the pwayew bewieved the univewse had spoken tuwu iwt thwough the wight thawt feww fwom the cwisp night sky of wintew, whewe a fweck of wight in the cownew of the pwayew's eye might be a staw a miwwion times as massive as the sun, boiwing its pwanets tuwu pwasma in owdew tuwu be visibwe fow a moment tuwu the pwayew, wawking home at the faw side of the univewse, suddenwy smewwing food, awmost at the famiwiaw doow, abouwt tuwu dweam again

awnd sometimes the pwayew bewieved the univewse had spoken tuwu iwt thwough the zewos awnd ones, thwough the ewectwicity of the wowwd, thwough the scwowwing wowds own a scween at the end of a dweam

awnd the univewse said i wove uwu

awnd the univewse said uwu have pwayed the gawme weww

awnd the univewse said evewything uwu need iws within uwu

awnd the univewse said uwu awe stwongew than uwu know

awnd the univewse said uwu awe the daywight

awnd the univewse said uwu awe the night

awnd the univewse said the dawkness uwu fight iws within uwu

awnd the univewse said the wight uwu seek iws within uwu

awnd the univewse said uwu awe nowt awone

awnd the univewse said uwu awe nowt sepawate fwom evewy othew thing

awnd the univewse said uwu awe the univewse tasting itsewf, tawking tuwu itsewf, weading its own code

awnd the univewse said i wove uwu because uwu awe wove.

awnd the gawme was ovew awnd the pwayew woke up fwom the dweam. Awnd the pwayew began a new dweam. Awnd the pwayew dweamed again, dweamed bettew. Awnd the pwayew was the univewse. Awnd the pwayew was wove.

uwu awe the pwayew.

wake up.
'''


[[dependencies.uwumod]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"


[[dependencies.uwumod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
